// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4RZxt3gISBEi2bGt08fndXqkYzPpLQyA',
    appId: '1:132050482758:android:df46ed022b1c81efa57c47',
    messagingSenderId: '132050482758',
    projectId: 'real-time-chat-a2558',
    storageBucket: 'real-time-chat-a2558.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZdNWZT9VD90905WFN7zCCERowRp2n4gs',
    appId: '1:132050482758:ios:290b69ab824c984ca57c47',
    messagingSenderId: '132050482758',
    projectId: 'real-time-chat-a2558',
    storageBucket: 'real-time-chat-a2558.appspot.com',
    androidClientId: '132050482758-otdm5p91phnfpro7390d5j44erj4liff.apps.googleusercontent.com',
    iosClientId: '132050482758-hm1q7lel3m7j0883mott2q5bal6r8b65.apps.googleusercontent.com',
    iosBundleId: 'com.example.realtimeChatApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyDqbh7LMxPW0vkrhc77EjHcSbTRjpHa8',
    appId: '1:132050482758:web:35f4922b6ff6466ca57c47',
    messagingSenderId: '132050482758',
    projectId: 'real-time-chat-a2558',
    authDomain: 'real-time-chat-a2558.firebaseapp.com',
    storageBucket: 'real-time-chat-a2558.appspot.com',
    measurementId: 'G-V52J04GLTG',
  );

}